#!/usr/bin/env bash

# Remember to edit in your credentials!

git config --global user.name NolanMadison ; git config --global nolan.madison777@gmail.com your_github_email_here
echo "Welcome back, Nolan :)"
echo -e "\n"
