#!/usr/bin/env bash

# Remember to edit in your credentials!

git config --global user.name your_github_username_here ; git config --global user.email your_github_email_here
echo "Welcome back, your_name_here!"
echo -e "\n"
